---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.7-bookworm

inputs:
  - name: dis-bundle-scheduler

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dis-bundle-scheduler/ci/scripts/build.sh
